spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/union
    username: union
    password: union
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: create

