spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/union
    username: union
    password: union
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update